### ISSUE TITLE
Hoping for improvements...

### ISSUE THREAD

**Issue by Jaff** [jnonino/terraform-aws-ecs-fargate#1]
I attempted integration of your module/project with our existing infrastructure. I was able to get a complete terraform plan/apply but it seems the configuration is incomplete. I'm including a link to gist of my ECS task-description: https://gist.github.com/Jaff/65ef1e87d0552a17880cbe25991c2ca7

**Comment by jnonino** [comment]
Hi, how are you? I was moving to another country so did not have time to look at this in the last days. Do you have any details regarding which is the missing configuration?

**Comment by jnonino** [comment]
Fixing in version 1.1.0
https://registry.terraform.io/modules/jnonino/ecs-fargate/aws/1.1.0

Please reopen if you need anything else.
