### ISSUE TITLE
Tasks using the Fargate launch type do not support ipcMode.

### ISSUE THREAD

**Issue by fabianmoronzirfas** [jnonino/terraform-aws-ecs-fargate#2]
Hi. I'm trying to use your module and I'm running into some issues. For example this one:  

```plain
Error: ClientException: Tasks using the Fargate launch type do not support ipcMode.
	status code: 400, request id: a68e7b4c-09f8-48a7-a6d3-80b1102b8c9c

  on .terraform/modules/ecs-fargate/jnonino-terraform-aws-ecs-fargate-4abc83f/server.tf line 36, in resource "aws_ecs_task_definition" "td":
  36: resource "aws_ecs_task_definition" "td" {

```
When I comment this line out I can start a container. https://github.com/jnonino/terraform-aws-ecs-fargate/blob/a82f375c4ba24b2a78441961701ee608c0f117d2/server.tf#L42

**Comment by jnonino** [comment]
Fixed in version 2.0.2
https://registry.terraform.io/modules/jnonino/ecs-fargate/aws/2.0.2
