### ISSUE TITLE
Feature Request: Scheduled Tasks

### ISSUE THREAD

**Issue by fabianmoronzirfas** [jnonino/terraform-aws-ecs-fargate#4]
Last one.

I'm actually trying to create a scheduled task that runs my container from a cron expression. Do you have any hints or ideas how I can provision something like this?  

I'm pretty new to terraform so any hint our example you can point me to would be highly appreciated.

**Comment by fabianmoronzirfas** [comment]
using 
Terraform v0.12.3
+ provider.aws v2.18.0

**Comment by fabianmoronzirfas** [comment]
I guess as I understand it this is out of the scope of this module.

**Comment by jnonino** [comment]
Yes, seems out of scope for this module but let me do some research and probably I can create another module for your requirement

**Comment by fabianmoronzirfas** [comment]
Thank you. Very kind of you. I already managed to build scheduled task on fargate, but I would love to get some input on it. I'm sure there are some unnecessary things in there. I'll be out of office for two weeks. I'll get back to you once I'm back.

**Comment by jnonino** [comment]
Great, when you come back take a look at this module and let me know you comments.

https://registry.terraform.io/modules/jnonino/ecs-fargate-scheduled-task/aws

**Comment by fabianmoronzirfas** [comment]
Hey @jnonino thanks for wipping together that module. I'm currently pretty happy with my solution. I'd like to learn a little more about terraform. So writing it by myself helps with that. 😄 Would you mind to take a look at this setup and tell me if there are some mistakes in there? https://github.com/fabianmoronzirfas/tf-scheduled-task
